apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yzxieh5ar-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:6bdeee2a6a15ce0d8e02f6ad5030cccf388d042a@sha256:0db2c6121da0e16c608b85ccdd55a0e302f8e3fc162bf579bc86cd6a44a6546c
          name: container-image
